name: Build and Publish pg_lake Docker Image

on:
  schedule:
    # Run once a week Sunday at UTC midnight
    - cron: "0 0 * * SUN"
  # Allows manual triggering
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/pg_lake-postgres
  PGDUCK_IMAGE_NAME: ${{ github.repository_owner }}/pgduck-server

jobs:
  build-push-cleanup-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for Release
      packages: write
      id-token: write # Needed for attestation
      actions: read # Required for attestation
      attestations: write

    steps:
      - name: Clone pg_lake repository
        run: |
          git clone https://github.com/Snowflake-Labs/pg_lake.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up space on runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo apt-get clean

      - name: Build pg_lake-postgres
        working-directory: ./pg_lake/docker
        run: docker compose build

      - name: Tag the pg_lake-postgres image for GitHub packages
        run: |
          IMAGE_ID=docker-pg_lake-postgres
          VERSION="latest"
          docker tag $IMAGE_ID:${VERSION} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
          docker rmi $IMAGE_ID:${VERSION}

      - name: Push pg_lake-postgres Docker image
        id: push
        run: |
          DIGEST=$(docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest | grep digest | awk '{print $3}')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "Pushed image with digest: $DIGEST"

      - name: Tag the pgduck-server image for GitHub packages
        run: |
          IMAGE_ID=docker-pgduck-server
          VERSION="latest"
          docker tag $IMAGE_ID:${VERSION} ${{ env.REGISTRY }}/${{ env.PGDUCK_IMAGE_NAME }}:${VERSION}
          docker rmi $IMAGE_ID:${VERSION}

      - name: Push pgduck-server Docker image
        id: pgduck_push
        run: |
          DIGEST=$(docker push ${{ env.REGISTRY }}/${{ env.PGDUCK_IMAGE_NAME }}:latest | grep digest | awk '{print $3}')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "Pushed image with digest: $DIGEST"

      - name: Delete older package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: "pg_lake-postgres"
          package-type: "container"
          min-versions-to-keep: 1 # Keep only the most recent version
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older pgduck package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: "pgduck-server"
          package-type: "container"
          min-versions-to-keep: 1 # Keep only the most recent version
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation for pg_lake-postgres
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for pgduck-server
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.PGDUCK_IMAGE_NAME }}
          subject-digest: ${{ steps.pgduck_push.outputs.digest }}
          push-to-registry: true
